### ISSUE TITLE
"once_mode" not found

### ISSUE THREAD

**Issue by zhiwen95** [BalloonUpdate/ModClient#2]
![image](https://user-images.githubusercontent.com/14962143/186145025-9bff20dd-c58b-4c55-8e0e-7a0feb5a3d25.png)

**Comment by asforest** [comment]
Check the field `once_mode` exists and make sure it is not commented in your config.yml if you are using LittleServer(aka 单文件服务端). Or in index.json for StaticServer(aka 静态服务端).

---

检查是不是把服务端配置文件里的once_mode字段给注释了，或者名字写错了

**Comment by zhiwen95** [comment]
thanks
