### ISSUE TITLE
似乎与LLibrary冲突

### ISSUE THREAD

**Issue by Mikm159** [BalloonUpdate/ModClient#3]
![5OWA)Z_704Z0CV%21X(IXNT](https://user-images.githubusercontent.com/99482689/192142681-0b1aff06-af22-4fc5-b7d5-6d1b7d60bed8.png)
[minecraft-exported-logs-2022-09-25T20-09-47.log](https://github.com/BalloonUpdate/ModClient/files/9640697/minecraft-exported-logs-2022-09-25T20-09-47.log)
崩溃稳定触发

**Comment by Mikm159** [comment]
https://mclo.gs/jUcNTiR

**Comment by KasumiNova** [comment]
尝试 1.1.0-Stable 版本，
请提供完整日志和对应的整合包。

**Comment by KasumiNova** [comment]
尝试对 LibrarianLib 降级后解决此问题。
